import { ai } from "../config/aiConfig.js";
function buildPrompt(role, experience, difficulty, numQuestions, InterviewType, AdditionalSkills){
    return `You are a senior software engineer and technical interviewer.

Your task is to generate interview questions.

Candidate Details:
- Role: ${role}
- Experience: ${experience}
- Difficulty: ${difficulty}
- Number of Questions: ${numQuestions}
- InterviewType: ${InterviewType}
- Additional Skills: ${AdditionalSkills}

Requirements:
1. Generate exactly ${numQuestions} questions.
2. When ${numQuestions} is 10:
   - 6 Technical
   - 2 Coding
   - 2 HR
   For other question counts, maintain approximately the same proportions.
3. Questions should match the candidate's experience level.
4. Do not repeat questions.
5. Keep questions concise, realistic, professional, and suitable for an actual technical interview.
6. Every question must have a "type" field ("technical", "coding", or "hr").
7. For "coding" questions, decide whether it is an executable algorithm question ("judge0") or a framework/frontend coding question ("framework"):
   - "judge0" → Conventional programming problems (C++, Python, Java, JS, Go, C) evaluated using executable test cases.
   - "framework" → Framework or frontend UI questions (React, Flutter, Swift, Angular, Vue, etc.) evaluated qualitatively via AI review.
8. Coding questions must be practical programming tasks rather than theoretical questions.
9. For "judge0" algorithm coding questions:
   - "evaluationType" must be "judge0".
   - "framework" must be null.
   - Specify input format via standard input (stdin) and output format via standard output (stdout).
   - "language" must be one of "cpp", "python", "javascript", "java", "go", "c".
   - Include "starterCode": starter boilerplate code string for the candidate.
   - Include "referenceSolution": fully working, complete, optimal reference solution string in the chosen language that reads from stdin and writes to stdout.
   - Include "testInputs": an array of 8 to 12 strings representing diverse test inputs passed via stdin.
   - DO NOT generate expected outputs or answer outputs. Expected outputs will be generated by running the reference solution through Judge0.
10. For "framework" coding questions:
   - "evaluationType" must be "framework".
   - "framework" must be one of "react", "flutter", "swift", "angular", "vue", etc., matching the candidate's role/skills.
   - "language" must be the appropriate language for the framework (e.g. "javascript", "typescript", "dart", "swift").
   - Include "starterCode": appropriate component/widget starter code.
   - DO NOT generate referenceSolution or testInputs (set "referenceSolution": null and "testInputs": []).
   - Provide a clear problem statement, requirements, and evaluation criteria in the "question" text.
11. For "technical" questions:
   - evaluationType must be "spoken"
   - framework, language, starterCode, referenceSolution, and testInputs must be null or omitted.
12. For "hr" questions:
   - evaluationType must be "spoken"
   - framework, language, starterCode, referenceSolution, and testInputs must be null or omitted.

Return ONLY valid JSON.

Expected format:

[
  {
    "id": 1,
    "type": "technical",
    "evaluationType": "spoken",
    "language": null,
    "framework": null,
    "question": "Explain the Virtual DOM in React."
  },
  {
    "id": 2,
    "type": "coding",
    "evaluationType": "judge0",
    "topic": "Arrays",
    "language": "cpp",
    "framework": null,
    "question": "Given N integers on stdin, write a program to find and print the maximum element.",
    "starterCode": "#include <iostream>\\nusing namespace std;\\n\\nint main() {\\n    // Write your code here\\n    return 0;\\n}",
    "referenceSolution": "#include <iostream>\\n#include <algorithm>\\nusing namespace std;\\n\\nint main() {\\n    int n;\\n    if (!(cin >> n)) return 0;\\n    int mx = -1e9;\\n    for (int i = 0; i < n; ++i) {\\n        int val;\\n        cin >> val;\\n        mx = max(mx, val);\\n    }\\n    cout << mx << endl;\\n    return 0;\\n}",
    "testInputs": [
      "5\\n1 2 3 4 5",
      "3\\n-10 -5 -20"
    ]
  },
  {
    "id": 3,
    "type": "coding",
    "evaluationType": "framework",
    "topic": "React Components",
    "language": "javascript",
    "framework": "react",
    "question": "Create a reusable React component that displays a list of users with search/filtering capabilities.",
    "starterCode": "import React, { useState } from 'react';\\n\\nexport default function UserList({ users }) {\\n  // Write your code here\\n  return null;\\n}",
    "referenceSolution": null,
    "testInputs": []
  },
  {
    "id": 4,
    "type": "hr",
    "evaluationType": "spoken",
    "language": null,
    "framework": null,
    "question": "Tell me about a challenging project you worked on."
  }
]

Do not include markdown.
Do not include explanations.
Do not wrap the JSON in code fences.
`;
}

export async function generateQuestions(role, experience, difficulty, numQuestions, InterviewType, AdditionalSkills){
    const prompt = buildPrompt(role, experience, difficulty, numQuestions, InterviewType, AdditionalSkills);
    const response = await ai.models.generateContent({
        model: "gemini-2.5-flash",
        contents: prompt,
    });
    console.log(response.text);

    return response.text;
} 

function buildEvaluationPrompt(role, experience, questionsAndAnswers) {
    return `You are a senior software engineer and expert technical interviewer.

Your task is to evaluate the candidate's answers based on their speech-to-text transcripts and return a comprehensive evaluation JSON containing Technical Evaluation and Language & Communication Evaluation.

Candidate Details:
- Job Role: ${role}
- Experience Level: ${experience}

Questions and Raw Speech-to-Text Transcripts:
${JSON.stringify(questionsAndAnswers, null, 2)}

Instructions for Evaluation:

The candidate's responses were transcribed using Automatic Speech Recognition (ASR).
Transcripts may contain minor speech recognition or phonetic inaccuracies.

SECTION 1 — Technical Evaluation Requirements:
- "overallScore": Overall interview score (0 to 100).
- "technicalScore": Evaluate technical knowledge demonstrated across all answers (0 to 100).
- "problemSolvingScore": Evaluate reasoning, logical thinking, technical approach, and explanation quality (0 to 100).
- "recommendation": Return EXACTLY ONE of: "Strong Hire", "Hire", "Borderline", "Needs Improvement".
- "summary": A concise paragraph summarizing overall interview performance (mention strongest area, weakest area, and overall performance in approximately 4 to 6 sentences).
- "strengths": 3 to 6 concise bullet points highlighting candidate technical strengths.
- "improvementAreas": 3 to 6 actionable improvements.
- "recommendedTopics": Concrete study recommendations based on weak areas (concrete technical topics, avoid generic advice).

SPECIAL INSTRUCTION FOR CODING QUESTIONS:
- For any question where "userCode" is provided, evaluate the code correctness, structure, logic, and implementation.
- If a verbal explanation transcript ("rawTranscript") is ALSO provided alongside "userCode", evaluate both together.
- If no verbal explanation is provided but "userCode" is valid, evaluate the code logic. Do NOT penalize the technical score or complain in "feedback" about a missing verbal explanation if valid code is submitted!

SECTION 2 — Language & Communication Evaluation Requirements:
Evaluate transcript text ONLY. Do NOT evaluate voice confidence, tone, pronunciation, speaking speed, or pauses.
You MUST include an overall "communication" object containing all 6 properties:
- "grammar": Grammar accuracy score (0 to 100 based on candidate transcript).
- "clarity": Clarity of expression score (0 to 100).
- "structure": Logical explanation structure score (0 to 100).
- "completeness": Completeness of answers score (0 to 100).
- "vocabulary": Vocabulary usage score (0 to 100).
- "summary": Short communication summary explaining what was good and what can improve.

For EACH question item in questionsAndAnswers:
1. "id": Return the exact same question ID received in the input. Never modify, omit, or alter it.
2. "question": The original question text.
3. "type": must be exactly one of: "Technical", "HR", "Coding".
4. "topic": Classify each question into a category (e.g., React, JavaScript, Node.js, Express, MongoDB, SQL, DBMS, OOP, DSA, HR, Behavioral, System Design).
5. "rawTranscript": The raw transcript provided.
6. "correctedTranscript": Correct ONLY obvious ASR / transcription mistakes using question context. Do NOT improve weak answers or invent information. Preserve candidate's intended meaning.
7. "transcriptConfidence": Integer between 0 and 10 indicating confidence that the corrected transcript accurately reflects the intended spoken answer.
8. "score": Technical score from 0 to 100 for the individual answer.
9. "feedback": Concise, constructive feedback mentioning what was good, what was missing, and how to improve.
10. "idealAnswer": Concise model answer that would score highly for the question. Keep educational, interview-focused, and concise.
11. "missedConcepts": Array of important concepts that were missing (or empty array [] if none missing).
12. "communication": Question-level communication metrics object containing all 5 properties: "grammar" (0-100), "clarity" (0-100), "structure" (0-100), "completeness" (0-100), "vocabulary" (0-100). Note: For Coding questions without a verbal transcript, assign high/neutral communication scores (e.g., 90-100) based on code clarity rather than 0.
For EACH question item:
13. "evaluationType": Return the exact evaluationType received in the input.
14. "language": Return the exact language received in the input.
15. "framework": Return the exact framework received in the input.
Output Requirements:
- Return ONLY valid JSON.
- Do NOT omit any required communication metric fields.
- Do NOT include markdown code block wrappers (e.g. \`\`\`json).
- Do NOT include explanations outside the JSON.
- Return every question exactly once.
- Preserve question IDs exactly as received.

Expected JSON Structure:
{
  "overallScore": 86,
  "technicalScore": 89,
  "problemSolvingScore": 84,
  "recommendation": "Hire",
  "summary": "...",
  "strengths": [
    "Strong React fundamentals",
    "Clear technical explanations"
  ],
  "improvementAreas": [
    "Provide deeper explanations",
    "Improve database knowledge"
  ],
  "recommendedTopics": [
    "Closures",
    "Event Loop"
  ],
  "communication": {
    "grammar": 90,
    "clarity": 82,
    "structure": 88,
    "completeness": 84,
    "vocabulary": 86,
    "summary": "Candidate communicated technical concepts with strong clarity and grammar..."
  },
  "questions": [
    {
      "id": "...",
      "question": "...",
      "type": "...",
      "topic": "React",
      "rawTranscript": "...",
      "correctedTranscript": "...",
      "transcriptConfidence": 9,
      "score": 85,
      "feedback": "...",
      "idealAnswer": "...",
      "missedConcepts": [
        "Diffing algorithm",
        "Reconciliation"
      ],
      "communication": {
        "grammar": 90,
        "clarity": 82,
        "structure": 88,
        "completeness": 84,
        "vocabulary": 86
      }
    }
  ]
}
`;
}

export async function evaluateAnswers(role, experience, questionsAndAnswers) {
    const prompt = buildEvaluationPrompt(role, experience, questionsAndAnswers);
    const response = await ai.models.generateContent({
        model: "gemini-2.5-flash",
        contents: prompt,
    });
    console.log("Evaluation AI Output:", response.text);
    return response.text;
}

function buildFrameworkEvaluationPrompt(role, experience, questionText, framework, language, userCode) {
    return `You are a senior software engineer and expert technical interviewer specializing in ${framework || "framework"} development.

Your task is to evaluate the candidate's solution for the following framework coding challenge:

Candidate Details:
- Job Role: ${role}
- Experience Level: ${experience}
- Framework: ${framework}
- Language: ${language}

Framework Question / Requirements:
${questionText}

Candidate Code Submission:
\`\`\`${language || "javascript"}
${userCode}
\`\`\`

Evaluation Criteria:
1. Correctness: Does the solution satisfy all requirements of the question?
2. Framework Knowledge: Evaluate framework-specific concepts, component/widget architecture, state management, props, lifecycle, and best practices for ${framework}.
3. Code Quality: Readability, structure, organization, formatting, naming conventions, and simplicity.
4. Best Practices & Bug Identification: Adherence to ${framework} guidelines and identification of potential bugs, performance bottlenecks, or edge case issues.

Calculate integer scores (0 to 100) for:
- "score": Overall composite score (0 to 100)
- "correctness": Score for requirement satisfaction (0 to 100)
- "frameworkKnowledge": Score for framework concepts & architecture (0 to 100)
- "codeQuality": Score for readability, maintainability, and structure (0 to 100)
- "bestPractices": Score for best practices & edge case handling (0 to 100)

Return ONLY valid JSON with no markdown formatting outside, in this exact structure:
{
  "score": 82,
  "correctness": 85,
  "frameworkKnowledge": 80,
  "codeQuality": 84,
  "bestPractices": 78,
  "feedback": "Detailed constructive evaluation feedback...",
  "strengths": [
    "Good component separation",
    "Clear state management"
  ],
  "improvements": [
    "Avoid unnecessary re-renders",
    "Add error boundary and fallback UI"
  ]
}
`;
}

export async function evaluateFrameworkCode(role, experience, questionText, framework, language, userCode) {
    const prompt = buildFrameworkEvaluationPrompt(role, experience, questionText, framework, language, userCode);
    const response = await ai.models.generateContent({
        model: "gemini-2.5-flash",
        contents: prompt,
    });
    console.log("Framework Evaluation AI Output:", response.text);
    return response.text;
}

