import mongoose from "mongoose";

const interviewSchema = new mongoose.Schema(
  {
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },

    jobRole: {
      type: String,
      required: true,
    },

    experienceLevel: {
      type: String,
      required: true,
    },

    difficulty: {
      type: String,
      required: true,
    },

    interviewType: {
      type: String,
      required: true,
    },

    numQuestions: {
      type: Number,
      required: true,
    },

    additionalSkills: {
      type: String,
    },

    questions: [
      {
        question: {
          type: String,
          default: "",
        },

        type: {
          type: String,
          default: "Technical",
        },

        topic: {
          type: String,
          default: "",
        },

        // =========================
        // Speech / Communication
        // =========================

        transcriptRaw: {
          type: String,
          default: "",
        },

        transcriptCorrected: {
          type: String,
          default: "",
        },

        transcriptConfidence: {
          type: Number,
          default: 0,
        },

        // =========================
        // Coding Question
        // =========================

        language: {
          type: String,
          default: "cpp",
        },

        starterCode: {
          type: String,
          default: "",
        },

        userCode: {
          type: String,
          default: "",
        },

        // Trusted solution used by the backend
        // to calculate expected outputs.
        // NEVER expose this to the candidate frontend.
        referenceSolution: {
          type: String,
          default: "",
        },

        // =========================
        // Coding Test Cases
        // =========================

        testCases: [
          {
            input: {
              type: String,
              required: true,
            },

            // Generated by executing the
            // reference solution through Judge0.
            expectedOutput: {
              type: String,
              default: "",
            },

            // false = visible/sample test
            // true  = hidden test
            isHidden: {
              type: Boolean,
              default: true,
            },
          },
        ],

        // =========================
        // Coding Execution
        // =========================

        codeOutput: {
          type: String,
          default: "",
        },

        executionStatus: {
          type: String,
          default: "",
        },

        codingEvaluation: {
          totalTests: {
            type: Number,
            default: 0,
          },
          passedTests: {
            type: Number,
            default: 0,
          },
          score: {
            type: Number,
            default: 0,
          },
          status: {
            type: String,
            default: "",
          },
          testResults: [
            {
              testCase: Number,
              passed: Boolean,
              actualOutput: String,
              status: String,
              isHidden: Boolean,
            },
          ],
        },

        // =========================
        // Answer / Evaluation
        // =========================

        answer: {
          type: String,
          default: "",
        },

        feedback: {
          type: String,
          default: "",
        },

        score: {
          type: Number,
          default: 0,
        },

        idealAnswer: {
          type: String,
          default: "",
        },

        missedConcepts: {
          type: [String],
          default: [],
        },

        // =========================
        // Communication Evaluation
        // =========================

        communication: {
          grammar: {
            type: Number,
          },

          clarity: {
            type: Number,
          },

          structure: {
            type: Number,
          },

          completeness: {
            type: Number,
          },

          vocabulary: {
            type: Number,
          },
        },

        // =========================
        // Speaking Analytics
        // =========================

        speakingAnalytics: {
          duration: {
            type: Number,
            default: 0,
          },

          wordCount: {
            type: Number,
            default: 0,
          },

          wordsPerMinute: {
            type: Number,
            default: 0,
          },

          pace: {
            type: String,
            default: "Slow",
          },
        },

        // =========================
        // Audio
        // =========================

        audio: {
          url: String,
          publicId: String,
          duration: Number,
          format: String,
        },
      },
    ],

    // =========================
    // Overall Interview Evaluation
    // =========================

    overallScore: {
      type: Number,
      default: 0,
    },

    technicalScore: {
      type: Number,
      default: 0,
    },

    problemSolvingScore: {
      type: Number,
      default: 0,
    },

    recommendation: {
      type: String,
      default: "Needs Improvement",
    },

    summary: {
      type: String,
      default: "",
    },

    strengths: {
      type: [String],
      default: [],
    },

    improvementAreas: {
      type: [String],
      default: [],
    },

    recommendedTopics: {
      type: [String],
      default: [],
    },

    // =========================
    // Overall Communication
    // =========================

    communication: {
      grammar: {
        type: Number,
      },

      clarity: {
        type: Number,
      },

      structure: {
        type: Number,
      },

      completeness: {
        type: Number,
      },

      vocabulary: {
        type: Number,
      },

      summary: {
        type: String,
        default: "",
      },
    },

    // =========================
    // Overall Speaking Analytics
    // =========================

    speakingAnalytics: {
      totalSpeakingTime: {
        type: Number,
        default: 0,
      },

      totalWordCount: {
        type: Number,
        default: 0,
      },

      averageWordsPerMinute: {
        type: Number,
        default: 0,
      },

      overallPace: {
        type: String,
        default: "Slow",
      },
    },

    // =========================
    // Interview Status
    // =========================

    status: {
      type: String,
      enum: ["Pending", "Completed"],
      default: "Pending",
    },
  },

  {
    timestamps: true,
  }
);

export default mongoose.model("Interview", interviewSchema);
